server:
    port: 9090

management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    scheduleDelivery:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException
      ignoreExceptions:
    payment:
          registerHealthIndicator: true
          ringBufferSizeInClosedState: 5
          ringBufferSizeInHalfOpenState: 3
          waitDurationInOpenState: 10s
          failureRateThreshold: 50
          recordExceptions:
            - org.springframework.web.client.HttpServerErrorException
            - java.io.IOException
            - java.util.concurrent.TimeoutException
            - org.springframework.web.client.ResourceAccessException
            - org.springframework.web.client.HttpClientErrorException
          ignoreExceptions: